### ISSUE TITLE
FactoryGirl and Ffaker: Getting uniqueness validation errors when not placing Ffaker calls in blocks

### ISSUE THREAD

**Issue by jmuheim** [ffaker/ffaker#121]
Model:

``` ruby
class User < ActiveRecord::Base
  validates :name, presence: true
end
```

Factory:

``` ruby
FactoryGirl.define do
  factory :user do
    name Faker::Name.name
  end
end
```

This results in uniqueness validation errors when doing `create :user` more than once. When packing `Faker` calls into `{ blocks }` it's working though:

``` ruby
FactoryGirl.define do
  factory :user do
    name { Faker::Name.name }
  end
end
```

Is this expected behavior? And if so, why?

**Comment by BKSpurgeon** [comment]
Further to EmmanuelOga's response, for those later looking at it [this](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#dependent-attributes) might help explain the issue:
