### ISSUE TITLE
Usernames are not random enough -- getting collisions in my specs

### ISSUE THREAD

**Issue by d11wtq** [ffaker/ffaker#19]
This happens very sporadically, but in tests I'm using ffaker to generate random usernames.  I was previously just using `ActiveSupport::SecureRandom.hex(16)`, but a colleague convinced me that ffaker was the way to go, so I switched and have had much success, besides this single issue.

In specs where I needs to create two or more users, sometimes, but not always (read, mostly not), ffaker generates the same username twice, which causes my specs to fail due to duplicate key conflicts in the database.  Re-running the test suite always corrects the issue.  My database is correctly cleaned between examples... this issue is localized to within a single example/test.

I think a possible solution (and maybe it actually exists but I don't see it), is for ffaker to strike out already used usernames, so that the same one cannot be generated twice, then provide some method to reset ffaker's dictionary so that all struck-out entries are released for re-use.  This way one can just reset ffaker in their setup/teardown logic.

**Comment by toupeira** [comment]
This looks like an outdated issue, FFaker now supports [unique results](https://github.com/ffaker/ffaker#unique-results) e.g. `FFaker::Name.unique.name`.
