### ISSUE TITLE
Releasing new gem versions

### ISSUE THREAD

**Issue by rstacruz** [ffaker/ffaker#202]
co-collaborators, what's our procedure for this?

cc @EmmanuelOga

**Comment by rocknruby** [comment]
* update the gemspec
* run tests `rake`

**Comment by EmmanuelOga** [comment]
Hey guys, glad to see all the stuff going on around here!

@rocknruby is right. If you guys want to coordinate releases, @rstacruz could be added as an admin on rubygems. I don't remember exactly but I think is something like gem owner --add=email@ofnewadmin.com. That has to be done by an admin.

**Comment by rstacruz** [comment]
hey, true, and its `gem owner ffaker -a hi@ricostacruz.com` :)

**Comment by rocknruby** [comment]
Owner added successfully.
Owners for gem: ffaker
- hi@ricostacruz.com
- hmaack@rocknruby.it
- 2112.oga@gmail.com
- emmanueloga@gmail.com

**Comment by rstacruz** [comment]
we should probably release a new version:

https://github.com/EmmanuelOga/ffaker/blob/master/Changelog.md

**Comment by rocknruby** [comment]
this is already done
