### ISSUE TITLE
FFaker::Avatar

### ISSUE THREAD

**Issue by itsdn** [ffaker/ffaker#204]
```ruby
NameError: uninitialized constant FFaker::Avatar
/lib/tasks/populate.rake:11:in `block (3 levels) in <top (required)>'
```

Avatar.image uninitialized.

UPD: Not yet released.

**Comment by rstacruz** [comment]
try adding `require 'ffaker'` on top of that rake file.

**Comment by tachyons** [comment]
same issue here , I think Avatar is not included in the released gem

**Comment by romanvbabenko** [comment]
+1 it's true, got the same issue

**Comment by rstacruz** [comment]
@EmmanuelOga time for a release?

**Comment by EmmanuelOga** [comment]
@rstacruz I'm ok with a release anytime, after all my last commit was maybe a year ago? :smile_cat: 

I was thinking maybe we want to create an organization, github.com/fakerlib or something like that? (so the people that's actually involved with the project can manage it). 

I'm surprised at the amount of fake data we have amassed. Would be nice to try and create ports to other languages... 

After that: world domination. But I'm getting ahead of myself.

**Comment by rstacruz** [comment]
heheh its alright man, even i have projects that people have taken over long after i've stopped using them, happens to all of us. `ffaker` would be an alright org name.

**Comment by EmmanuelOga** [comment]
Gotcha!

Ah! github.com/ffaker is available.

**Comment by rocknruby** [comment]
:+1: for organization :+1: for release
