### ISSUE TITLE
FFaker uis faster ?! who determine this ?! and does benchmark exist to validate this statement ?! 

### ISSUE THREAD

**Issue by vveliev** [ffaker/ffaker#233]
what makes FFaker faster than Faker ?!

**Comment by rocknruby** [comment]
@vveliev have you read the readme ? -- https://github.com/ffaker/ffaker#ffaker-is-faster-does-it-really-matter

**Comment by vveliev** [comment]
yes , I did  and see no reason behind....

**Comment by rocknruby** [comment]
To be honest I have no idea, it can be faster or maybe not. If you like you can start benchmarking. Would be interesting nowadays. And I guess @EmmanuelOga can give you a more detailed answer on your questions.

**Comment by EmmanuelOga** [comment]
Not sure what you mean "uis", but added a PR to try to clarify the "speed" subject:

https://github.com/ffaker/ffaker/pull/239

**Comment by EmmanuelOga** [comment]
For curious people out there, faker used to be implemented like this:

```
def someGenerator
  sample([ GIGANTIC ARRAY OF RANDOM THINGS ])
end
```

..., so everytime you called someGenerator, the interpreter recreated the gigantic array, picked one element, and then returned, which not only was slow but also generated a lot of garbage.

These days faker uses YAML and the i18n gem, which probably has a bit more overhead than the simple data loading ffaker does, but doesn't have the flaw that I just described above.

**Comment by rocknruby** [comment]
I close this issue now. @EmmanuelOga did some changes in the Readme file. #239
