### ISSUE TITLE
Avatar could not download file: redirection forbidden

### ISSUE THREAD

**Issue by xifengzhu** [ffaker/ffaker#247]
when I try to use the ffaker(2.1) with carrierwave(0.10.0) , I got this problem:

```
ActiveRecord::RecordInvalid: Validation failed: Profile avatar could not download file: redirection forbidden: http://robohash.org/temporaconsequaturet.png?size=300x300 -> https://robohash.org/temporaconsequaturet.png?size=300x300
```

My code:
```ruby
class Profile < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end
```

`Profile.create(remote_avatar_url: FFaker::Avatar.image)`

**Comment by rocknruby** [comment]
Hi @xifengzhu, PR #241 changed the API and produces now only HTTPS robohash URLs. I'm sorry but isn't released yet.

**Comment by rocknruby** [comment]
@xifengzhu  I created #248 to release a new version of faker.
