### ISSUE TITLE
Release a new version of ffaker

### ISSUE THREAD

**Issue by rocknruby** [ffaker/ffaker#248]
Our last release is almost 6 month ago. And there are some important fixes and additions in the master.

Todos:

*  update the Changelog
* fixing the master

Anything else?

**Comment by rocknruby** [comment]
@marocchino @rstacruz

**Comment by rstacruz** [comment]
I'm a little outta the loop on this one, go with your gut :)

**Comment by rocknruby** [comment]
Me too, I'll try to create a stable master @rstacruz

**Comment by rocknruby** [comment]
Its done.
