### ISSUE TITLE
Regex repetition not working

### ISSUE THREAD

**Issue by jpesce** [ffaker/ffaker#249]
The *{min, max}* syntax doesn't work.

Eg:
```
> FFaker::String.from_regexp(/[0-9]{5}/)
 => "2{5}"
```

Expected result would be something like ```82621```

Reference: http://www.regular-expressions.info/repeat.html

**Comment by marocchino** [comment]
I think this one resolve with d690e66
@rocknruby isn't it released yet?

**Comment by rocknruby** [comment]
Not yet released but I will do it now. We just have to update the changelog @marocchino.

**Comment by rocknruby** [comment]
New version is released.
