### ISSUE TITLE
Configure Hound CI

### ISSUE THREAD

**Issue by itsdn** [ffaker/ffaker#251]
Some of the code (if not most) is written using single quotes. Hound CI complains every time someone submits a pull request with single quotes. I think we should pick one style and stick to it. I could submit a pull request with these changes, that will include converting all code to one style and adding Rubocop and Hound CI config files to the repo.

**Comment by rocknruby** [comment]
Yes please, its annoying. I prefer single quotes `'` instead of hounds configuration. If you like to do it, it would be a good improvement. I will not merge any other PR to avoid the conflict trouble.

**Comment by itsdn** [comment]
@rocknruby Fixed this in Pull request #253.

**Comment by rocknruby** [comment]
@itsdn - sweet thank you
