### ISSUE TITLE
NameError: uninitialized constant FFaker::IdentificationBR

### ISSUE THREAD

**Issue by hudsonsferreira** [ffaker/ffaker#280]
```
2.3.1 (main):0 > FFaker::IdentificationBR.cpf
NameError: uninitialized constant FFaker::IdentificationBR
```

**Comment by rocknruby** [comment]
Which version of ffaker you are using? 

`
➜  ffaker git:(master) irb

irb(main):001:0> require 'ffaker'
=> true

irb(main):002:0> FFaker::IdentificationBR.cpf
=> "63410530696"
`

**Comment by hudsonsferreira** [comment]
@rocknruby 2.2

**Comment by igortice** [comment]
I'm having the same problem for this version

**Comment by SagareGanesh** [comment]
@hudsonsferreira @igortice In ffaker-2.2.0, module **_IdentificationBR_** is missing. I dont know what is reason behind it. But If you want to work it correctly, add [ffaker/lib/ffaker/identification_br.rb](https://github.com/ffaker/ffaker/blob/master/lib/ffaker/identification_br.rb) file in your local gem at same location and bundle install.

Hope this will help you,
thanks.
