### ISSUE TITLE
FFaker::Color.hex_code 

### ISSUE THREAD

**Issue by veekram** [ffaker/ffaker#292]
I am not sure, why am i getting the following `NoMethodError`. I guess, it was supposed to work as:
[92] pry(main)> FFaker::Color.name
"blue"
But while trying to access hex_code and others except `name` method. 
[84] pry(main)> FFaker::Color.hex_code
NoMethodError: undefined method `hex_code' for FFaker::Color:Module
from (pry):80:in `__pry__'

**Comment by SagareGanesh** [comment]
Hi @veekram the reason behind **_`Faker::Color.name`_** is working correctly, and **_`Faker::Color.hex_code`_** is not is, In current version of ffaker i.e 2.2.0 the `FFaker::Color` module contains only one method which is `name`. I think we can able to use all other methods i.e `hex_code, rgb_array,  rgb_list, rgba_array, rgba_list, hsl_array, hsl_list, hsla_array, hsla_list` in next release.

**Comment by veekram** [comment]
@SagareGanesh Thank you for your response. I went through the documentation and found out those methods included. Thanks for letting me about it. Let's make it available on the next release. Cheeers!
