### ISSUE TITLE
FFaker::HTMLIpsum.p generates too much "fancy" content.

### ISSUE THREAD

**Issue by jdickey** [ffaker/ffaker#298]
The `count` parameter is honoured correctly when the `fancy` option is left at the default of `false`. Setting it to `true` adds more content than requested. This plays hob with client code that trusts that the number of sentences generated is as specified.

Reproduction:

``` ruby
$ pry
[1] pry(main)> require 'ffaker'
true
[2] pry(main)> FFaker::HTMLIpsum.p
"<p>Impedit eligendi delectus quia id quasi. Ipsum provident asperiores animi harum quasi accusantium. Laboriosam et perferendis doloremque consequatur.</p>"
[3] pry(main)> FFaker::HTMLIpsum.p 1
"<p>Tenetur nisi nulla voluptatum adipisci aliquid illo saepe consequatur.</p>"
[4] pry(main)> FFaker::HTMLIpsum.p 3
"<p>Vitae molestias quisquam omnis expedita maxime soluta quasi. Eaque ipsa consectetur ea doloremque non ullam. Rerum dolor est ea vel molestias natus. Quia dolores ducimus qui et eligendi nihil. Rem officiis ut ex sequi.</p>"
[5] pry(main)> FFaker::HTMLIpsum.p 3, fancy: true
"<p><em>Necessitatibus qui nobis sed est sint asperiores non. A quia delectus hic aut dolor suscipit inventore sed. Consequatur aut alias accusamus est deserunt accusantium quia. At cum ratione placeat molestiae. Vel sed eaque omnis debitis tempore perspiciatis quasi ipsam.</em> Laborum aut enim et qui mollitia quo. Illum iure dolorem et consectetur quisquam soluta atque corporis. Quia in magni nobis earum iure cum. Aut est molestiae nihil facere ut accusantium perferendis. Sequi fuga explicabo dolorem sint. <strong>Sint deleniti</strong>.</p>"
[6] pry(main)> exit
$
```

**Comment by jdickey** [comment]
`Faker::HTMLIpsum.p` occasionally generates more sentences than requested when `fancy` is left as `false`, though this seems to occur less frequently than when `fancy` is `true` (~15% of my FFaker-using code tests fail with `fancy` as `false` as opposed to ~60% with `fancy` set to `true`).

**Comment by Schwad** [comment]
Howdy @jdickey  - is this still an issue that we are having with the gem? Hope all is well!

**Comment by jdickey** [comment]
Hey, @Schwad, it's fine now. I just ran some tests against `HTMLIpsum.p` (calling `HTMLIpsum.p(3)` 10,000 times and counting the "sentences" in each returned string using

```ruby
  Set.new(results.map { |s| s.split('. ').join(".\n").split("\n").count }.sort)
```

which gives me resulting "sentence counts" limited to `[3, 4, 5]`. I'd say we can mark this bug as closed.

I was thinking about opening a feature request that would optionally eliminate the random-value add to the sentence count but, on further consideration, it probably isn't worth it.

Thanks for all your work!
