### ISSUE TITLE
FFaker NameErr breaks `rails console` command

### ISSUE THREAD

**Issue by ghost** [ffaker/ffaker#307]
This spec/factories/locations.rb file breaks `rails c` command.

```
FactoryGirl.define do
  factory :location do
    name { FFaker::Venue.name }
    latlon "POINT(#{FFaker::Geolocation.lng} #{FFaker::Geolocation.lat})"
  end
end
```
Can any friend point out what is wrong?

Error info:
```
/spec/factories/locations.rb:4:in `block (2 levels) in <top (required)>': uninitialized constant FFaker (NameError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:18:in `factory'
	from /Users/iPanda/Documents/rails/unfold/spec/factories/locations.rb:2:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /Users/iPanda/Documents/rails/unfold/spec/factories/locations.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/reload.rb:6:in `reload'
	from /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:24:in `block (2 levels) in <class:Railtie>'

```

POINT(-123, 23) is the value of a geolocation data, supported by postgis extension of postgresql database.

In `rpec` tests or in `rake db:seed`, this FFaker works fine.  Only the spec/factories file breaks the `rails c` command.

File db/seeds.rb
```
Location.create!([
  {
    name: "#{FFaker::Venue.name}",
    latlon: "POINT(#{FFaker::Geolocation.lng} #{FFaker::Geolocation.lat})"
  },
  {
    name: "#{FFaker::Venue.name}",
    latlon: "POINT(#{FFaker::Geolocation.lng} #{FFaker::Geolocation.lat})"
  }
])
```

**Comment by marocchino** [comment]
You should require it before use it.
Try again with:

```ruby 
require "ffaker"
```

>_<

**Comment by lukeipanda** [comment]
Adding this `require "ffaker"` will cause another error.
Once installed the gem, I can use FFaker modules with fully qualified names. See the seeds.rb doesn't cause a problem.
I had to remove `"POINT(#{FFaker::Geolocation.lng} #{FFaker::Geolocation.lat})"` from the spec factory file for now. Maybe it's not allowed in string interpolations. But it works fine in rspec tests. It just breaks the `rails c` command.

**Comment by PapePathe** [comment]
Which version of rails do you use? Maybe if we can reproduce this a solution may emerge..

**Comment by bifork** [comment]
5.0.0.1

**Comment by dsdshcym** [comment]
I encountered similar issue today:
1. I only put `ffaker` in `:test` group in my `Gemfile`
2. Then I had the `uninitialized constant FFaker (NameError)` when I opened a rails console
3. I moved `ffaker` into `:development, :test` group in `Gemfile`, then I could open console without any error

Hope this info could help

**Comment by marocchino** [comment]
Too late.
That's because of FactoryBot (FactoryGirl) loaded on development, and FFaker used in it.
You should load the same way with your FactoryBot(I mean deps).

**Comment by Volosh1n** [comment]
I think it could be closed
