### ISSUE TITLE
No .unique method

### ISSUE THREAD

**Issue by mstashev** [ffaker/ffaker#320]
$ rails db:seed
rails aborted!
NoMethodError: undefined method `unique' for FFaker::Internet:Module
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/db/seeds.rb:14:in `block in <top (required)>'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/db/seeds.rb:11:in `times'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/db/seeds.rb:11:in `<top (required)>'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:549:in `load_seed'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/bin/rails:9:in `require'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/bin/rails:9:in `<top (required)>'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/Users/mstashev/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/bin/spring:15:in `require'
/Users/mstashev/Documents/IronYard/GaleríaDeFotos/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by AlexAvlonitis** [comment]
https://github.com/ffaker/ffaker/pull/333

**Comment by marocchino** [comment]
released as v2.7.0

**Comment by AlexWayfer** [comment]
I think this issue can be closed.
