### ISSUE TITLE
FFaker and FactoryGirl

### ISSUE THREAD

**Issue by ClaudioCarmeli** [ffaker/ffaker#325]
Hello,
I am trying to generate 2 random locales for my Rails app. I am using factories.
I am currently trying something like:
```
factory User
  language_1 { examples.first }
  language_2 { examples.last }

  transient do
    examples { FFaker::Locale.language('random') }
  end
end
```
However this
* doesn't get 2 locales, but only 1.
* once I get the `language` or `code` for the locale, I can't grab the other one. How can I get a handle to the `locale` itself so that I can then call `language`  and/or `code` at a later stage?
* how can ensure to have unique picks? I can simply call `unique` using faker/forgery but I don't know how to do it with ffaker.

Awesome gem.
I'd really appreciate any help I can get on the matter.

**Comment by marocchino** [comment]
Since 2.7.0, you can do that like this:

```rb
factory User
  language_1 { FFaker::Locale.unique.language('random') }
  language_2 { FFaker::Locale.unique.language('random') }
end
```

**Comment by Volosh1n** [comment]
>doesn't get 2 locales, but only 1.

I'd suggest to simply put @marocchino suggestion into array, for example, like
```ruby
Array.new(2) { FFaker::Locale.unique.language('random') }
```

Reopen issue if we can help with something else. Thank you.
