### ISSUE TITLE
PhoneNumbers validation with telephone_number gem

### ISSUE THREAD

**Issue by nicolas-brousse** [ffaker/ffaker#343]
Hi,

I'm using FFaker to generate fake datas and [`telephone_number`](https://github.com/mobi/telephone_number) for phone number validation.  
But I often have errors from `FFaker::PhoneNumberXX.unique.international_mobile_phone_number` when I ask for validation.

I made test on: 
- `FFaker::PhoneNumberAU`
- `FFaker::PhoneNumberBR`
- `FFaker::PhoneNumberCU`
- `FFaker::PhoneNumberDA`
- `FFaker::PhoneNumberDE`

Then I tried with `FFaker::PhoneNumberID` and this one works. I didn't try the others for now.

My validator is:
```ruby
class User < ApplicationRecord
  before_validation :format_phone_number
  ...

  def format_phone_number
    telephone_number = TelephoneNumber.parse(phone_number)

    if telephone_number.valid?
      self.phone_number = telephone_number.e164_number
    else
      errors.add(:phone_number, "Phone number invalid")
    end
  end
```

Does it something we could improve on FFaker?

**Comment by hmaack** [comment]
Hi @nicolas-brousse . I investigates here just for fun: 

```ruby
modules = [FFaker::PhoneNumberAU.method(:unique), FFaker::PhoneNumberBR.method(:unique), FFaker::PhoneNumberCU.method(:unique), FFaker::PhoneNumberDA.method(:un
ique), FFaker::PhoneNumberDE.method(:unique)]

100.times do
   number = modules.sample.call.international_mobile_phone_number
   result = TelephoneNumber.parse(number).valid?
   result ? puts("🎉") : puts("#{number} is invalid for some reason")
end
```

Will result into: 

```
🎉
🎉
+45 08596589 is invalid for some reason
🎉
🎉
+61 5 5924 9911 is invalid for some reason
+61 5 2058 7296 is invalid for some reason
🎉
+45 84530410 is invalid for some reason
🎉
+61 4 6130 7480 is invalid for some reason
+61 5 1193 0358 is invalid for some reason
🎉
🎉
+45 13835431 is invalid for some reason
🎉
🎉
🎉
🎉
🎉
🎉
🎉
🎉
00535 928 6532 is invalid for some reason
00535 180 9161 is invalid for some reason
```

I will close this issue because of inactivity and hope I could help you with this snippet. Somehow the validator of your gem doesn't like those numbers 👎🏼 - but I guess you already made it 😇 

Thanks for your report, feel free to reopen this if you still need some help
