### ISSUE TITLE
FFaker::SSN.ssn generates invalid ssn

### ISSUE THREAD

**Issue by AmanShurafa** [ffaker/ffaker#348]
An SSN cannot start with a 9 or 666. It also cannot contain all zeros in one group
All of these are invalid:
9##-##-####
666-##-####
000-##-####
###-00-####
###-##-0000

FFaker does not take that into account:
```
irb(main):001:0> require 'FFaker'
=> true
irb(main):002:0> FFaker::SSN.ssn
=> "383-33-0697"
irb(main):003:0> FFaker::SSN.ssn
=> "952-69-5309"
```

**Comment by lilsweetcaligula** [comment]
Hi, what's the status of the issue? Will PRs be accepted?

Kind Regards,
lilsweetcaligula

**Comment by marocchino** [comment]
@lilsweetcaligula Yes, will be pleasure. 😄
