### ISSUE TITLE
uninitialized constant FFaker::Book

### ISSUE THREAD

**Issue by wonderer007** [ffaker/ffaker#363]
I am trying to get book title by
`FFaker::Book.title` but getting error `NameError: uninitialized constant FFaker::Book`

**Comment by adimasuhid** [comment]
@wonderer007 This happened to me a few days ago when I installed an old version of FFaker, specifically 2.1.0, which ended up not having the `Book` module yet. The latest version 2.9.0 has the `Book` module. `bundle update ffaker` or `gem update ffaker` might help.

**Comment by pradyumna2905** [comment]
I'm facing the same issue. Greenfield rails application. Attempting to use it along with `seed_fu` (https://github.com/mbleigh/seed-fu).

I'm getting `uninitialized constant FFaker::Bank`

**Comment by Devin-Chaves** [comment]
Had this issue in an old project. I had the ffaker dep in the wrong environment. Added it in test and development.

**Comment by Volosh1n** [comment]
Good there are examples of fix :relaxed: 
@wonderer007 , please reopen this issue if you still experiencing issues with Book module and we'll help. Thank you.
