### ISSUE TITLE
NameError: uninitialized constant FFaker::PhoneNumberTW

### ISSUE THREAD

**Issue by huier522** [ffaker/ffaker#378]
I am try to getting PhoneNumberTW, but it's not work.
I already upgrade to ffaker 2.10.0 (was 2.9.0)
thanks.

**Comment by Kutomore** [comment]
Could you provide a little more context please?

**Comment by Volosh1n** [comment]
`FFaker::PhoneNumberTW` methods works well and module exists. @huier522 , please, reopen issue with more info and we'll help. Thanks.
