### ISSUE TITLE
Genders list

### ISSUE THREAD

**Issue by alec-c4** [ffaker/ffaker#389]
Hi,
your genders list (https://github.com/ffaker/ffaker/blob/master/lib/ffaker/gender.rb) isn't full enough, please fill it with other genders. You can find some of missing genders here - https://www.wattpad.com/341462536-complete-list-of-genders-the-complete-list-of-all

**Comment by Bigbublik** [comment]
Демон :)

**Comment by vbrazo** [comment]
Sorry but this repo is abandoned.

**Comment by marocchino** [comment]
@alec-c4 Can you pr this?

**Comment by alec-c4** [comment]
@marocchino Unfortunately list of genders cannot be full enough independent of how many genders you adding :) for example - I'm sithsexual, I'm full of darkness, but there are no this gender in the list :)

**Comment by marocchino** [comment]
@alec-c4 Oh, I mean pull request. This is a concept that is rarely in my country. I would like someone who knows well to work on it to reduce mistakes.

**Comment by Volosh1n** [comment]
Good idea, but need specialist, who can provide list which is full enough. If someone can help us with that - it could be a good favor :smiley:
