### ISSUE TITLE
Returned name matching country name makes test fail

### ISSUE THREAD

**Issue by killerkiara** [ffaker/ffaker#390]
We have an issue when testing the deletion of an account. We test for:

`expect(page).not_to have_content child.first_name`

Even upon a successful request the test fails because the page contains a form with a country list containing "Dominica" which is also the `child.first_name` generated by:

`FFaker::Name.first_name`

The failure is of course random and occurs when the randomly generated name matches the country name.

**Comment by marocchino** [comment]
well, I thought about it.
The name Dominica might actually be there, so it would be better to fix the test case.

How about matching in a smaller scope?

```
within('.some-class') do
  expect(page).not_to have_content child.first_name
end
```

https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSession:within

I'm not sure if it's capybara, but I'm sure there's a similar syntax in other gems.

**Comment by killerkiara** [comment]
@marocchino Thanks for your reply! I know the solution with the `within` block on Capybara. However I don't like it super much when: 
- I need to add some classes/ids in the markup specifically to fix this test
- the expectations are set on the same form where the country list is so i really to check ONLY in the input field
- the error comes in WAY too many cases so I need a lot of these ad hoc fixes. Here is a list of the problematic names and last names:

name as:
- Dominica 
- Russ
last names:
- Green 
- Keeling

Also, it is to be noted that is very likely these names are set in a form where the country is also set, so they are really belonging to the same block in the markup.

**Comment by marocchino** [comment]
Sorry, Understand your problem, but Be not too motivated to modify this project.

> I need to add some classes/ids in the markup specifically to fix this test

BTW, You still have [another option](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) like `eq(0)` or `[name='xxx']`.

Or will can make filter something like:

```rb
FFaker::Name.reject { |x| %w[aaa bbb].include?(x) }.name
```

Are you want this?

**Comment by Volosh1n** [comment]
Seems to be not relating to gem issue, because those names are valid
