### ISSUE TITLE
FFaker::Internet email, safe_email and free_email generating invalid email addresses

### ISSUE THREAD

**Issue by Phitherek** [ffaker/ffaker#399]
In FFaker::Internet methods email, safe_email and free_email are generating email addresses with underscores which are not valid.

**Comment by Volosh1n** [comment]
Hi! Seems like some email services allow users to use underscores in their emails.
[There is](https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address) a good answer with links to mail protocol docs.
I'd use `gsub` on FFaker's `safe_email` to remove underscore if your app does not allow using underscores, so I could still use FFaker's data.
But anyway, as @marocchino decide.

**Comment by marocchino** [comment]
Well, I think erasing underscores in email generation rules is too dependent on certain services.
As suggested by @Volosh1n, gsub or tr will be fine here.(I recommend tr when replacing a single character, because it has better performance)

```rb
FFaker::Internet.email.tr('_', '.')
```

If you think this statement is too hard to read, we can add some config option like:

```rb
FFaker::Config do
  config.free_email_format = "%<frist_name>s.%<last_name>s%<host>s" # default will be "%<frist_name>s%<delimiter>s%<last_name>s%<host>s"
end
```

Although we need a lot of fixes.

**Comment by davidhrbac** [comment]
We have just upgraded ffaker 2.11.0 to 2.12.0 and specs fail with `Validation failed: Email is not a valid email`.

```FFaker::Internet.email.tr('_', '.')``` did not help.

**Comment by Volosh1n** [comment]
> We have just upgraded ffaker 2.11.0 to 2.12.0 and specs fail with `Validation failed: Email is not a valid email`.
> 
> `FFaker::Internet.email.tr('_', '.')` did not help.

Could you provide your email validation format? I think we could help make valid format for FFaker's random emails for you. It is not about bad data generation, it is about specific case, so it fixable situation.

**Comment by davidhrbac** [comment]
Good point, we use:

```ruby
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not a valid email") unless /\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i.match?(value.to_s)
  end
end
```

**Comment by Volosh1n** [comment]
I've created model with your email validation and checked it with email from `FFaker::Internet.email`. Generated email was with underscore and model was valid.
![Valid model](https://i.imgur.com/njLLygO.png)

Also, checked with Rubular. [Results](https://rubular.com/r/kjD1WNKsPs1KMI).
Sad, I have no idea what went wrong :disappointed: 

The other way to understand problems in those cases is checking generated values to be sure that it actually invalid email.

**Comment by davidhrbac** [comment]
Well, since there are no new releases, it's not easy to diff the releases...

**Comment by marocchino** [comment]
I suspect that this line is caused by not being able to delete the underbar. However, I did not find any problematic strings in the source name.
https://github.com/ffaker/ffaker/blob/4a597e99ff4bdc8015863f0892deb3bc5eae2958/lib/ffaker/internet.rb#L51

So now it seems like the easiest way to determine what string was the problem. You can exam failure emaill like this.

```rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    return if /\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i.match?(value.to_s)
    log.info { value } if Rails.env.test?
    record.errors[attribute] << (options[:message] || "is not a valid email") 
  end
end
```

**Comment by davidhrbac** [comment]
So, here we go:

```text
Validation failed: Email ardith_d'amore@bosco.biz is not a valid email
Validation failed: Email bev_o'hara@quitzon.biz is not a valid email
Validation failed: Email lai.o'keefe@hagenes.name is not a valid email
Validation failed: Email florentina.o'conner@tremblay.ca is not a valid email
Validation failed: Email aleen_d'amore@hamillschmeler.ca is not a valid email
Validation failed: Email rachel.o'hara@osinski.co.uk is not a valid email
```

**Comment by marocchino** [comment]
Oh, it was `'`. Thanks.

**Comment by davidhrbac** [comment]
This helped:
```ruby
FFaker::Internet.email.tr("'", ".")
```
But it is my fault, ```'``` is allowed by RFC. See https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

**Comment by marocchino** [comment]
> But it is my fault, `'` is allowed by RFC. See stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

You are right. But, I also fixed `Internet.user_name`, since almost services do not allow `'` in user name.

In term of `user_name`, an un-sanitized full name is just mistaken.
