### ISSUE TITLE
Failing `AddressJA` tests

### ISSUE THREAD

**Issue by AlexWayfer** [ffaker/ffaker#409]
The description from here: https://github.com/ffaker/ffaker/pull/314/files#r318543841

> I'm not an expert in Japanese, so I don't know how to fix it in more correct way, but not every entry from `lib/ffaker/data/address_ja/city` (lines 14, 20, 23–25, etc.) or even `lib/ffaker/data/address_jp/city` (line 40) has `市`. So, tests are randomly failing now.

**Comment by marocchino** [comment]
decided to erase not `市`. read the code and the `区` is covered by ward.
