### ISSUE TITLE
FFaker::PhoneNumberBR generating invalid area codes

### ISSUE THREAD

**Issue by JoaoFagundes** [ffaker/ffaker#454]
From https://github.com/ffaker/ffaker/blob/master/lib/ffaker/phone_number_br.rb, area codes are specified as 
```
AREA_CODE = [
  10..19, 21..22, 24, 27..28, 31..35, 37..38, 41..49,
  51..54, 55, 61..69, 71..75, 77, 79, 81..89, 91..99
]
```

but there are a few invalid area codes in this constant, such as `10`, `52` and `72`

sources: 
- https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Brazil
- https://www.vidadeturista.com/ddds-do-brasil

**Comment by CarlosMouraJR** [comment]
Hello my friend,
recently i opened a PR to fix this problem.

#457
