### ISSUE TITLE
placeholder image request leading to Net::OpenTimeout: execution expired

### ISSUE THREAD

**Issue by tansaku** [ffaker/ffaker#463]
I'm using ffaker version 2.17.0 with ruby 2.6.6 on OSX 10.15.7 and I seem to be having trouble getting images through from placeholder.com.  I get this error:

```
Net::OpenTimeout: execution expired
/Users/tansaku/.rvm/gems/ruby-2.6.6/gems/ffaker-2.17.0/lib/ffaker/image.rb:45:in `download_file'
```
I can access placeholder.com fine from the browser e.g. https://via.placeholder.com/300x300/ and it also works fine over curl:

```
$ curl https://via.placeholder.com/300x300/ --output ~/tmp/placeholder.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1132  100  1132    0     0   1702      0 --:--:-- --:--:-- --:--:--  1699

```

I swapped out the url in ffaker image.rb for https://placeimg.com/640/480/any and that worked fine.  

Has anyone else experienced this? ffaker being unable to grab images from placeholder for some reason?

Maybe some difference in the HTTP headers/user-agent being sent in each context?   Some throttling of my IP at placeholder?  I only ever used the feature for the first time today ...

**Comment by Volosh1n** [comment]
Hi, @tansaku 
Thanks for report. Could you, please, tell if you still experience this behavior of FFaker's Image? I've tried several times today, but seems it is working fine now.

**Comment by tansaku** [comment]
Thanks @Volosh1n - I tried again today and I still have the same issue.  I tried and failed on two different computers yesterday (both on the same network).  Maybe it's specific to the network I'm on?  I guess I'll need to break out something to trace the actual http request to compare to what happens with the browser or curl operations that do work ... sounds like I'm in some sort of weird corner case ... 

I just tried it tethering by my iPhone and that did work (!), so I guess there's something about the request or the site itself that's being blocked in just the ruby client when I'm on my main BT business network ... I'll see if I can pull up the raw requests for comparison

**Comment by tansaku** [comment]
Here's the successful request going through in firefox on my bt network:

```
GET /400x300/0ab6bc/60d890.png?text= HTTP/1.1
Host: via.placeholder.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: xxxxx
Upgrade-Insecure-Requests: 1
```
I'm trying to trace the underlying ruby http request with limited success - can't seem to get things showing up in wireshark.  Simulating all the headers is not helping:

```
Kernel.open('https://via.placeholder.com/300x300/0ab6bc/60d890.png?text=',
    "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0",
    "Accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language" => "en-US,en;q=0.5",
    "Accept-Encoding" => "gzip, deflate, br",
    "Connection" => "max-age=0",
    "Upgrade-Insecure-Requests" => "1",
    "If-Modified-Since" => "Mon, 16 Nov 2020 11:19:22 GMT",
    "If-None-Match" => "5fb2603a-46c",
    "Cache-Control" => "max-age=0")
```

**Comment by hmaack** [comment]
I can reproduce this. Like @tansaku said, even while using `net/http` with all headers it's somehow blocked. Maybe placeholder.com doesn't like ruby clients anymore. https://placeholder.com/rules
