### ISSUE TITLE
Invalid country and country code

### ISSUE THREAD

**Issue by fishballzzz** [ffaker/ffaker#477]
`Hong Kong` and `Macao` are just provinces in China and they should not be listed in https://github.com/ffaker/ffaker/blob/main/lib/ffaker/data/address/country.

**Comment by Volosh1n** [comment]
@fishballzzz thank you for your attention. Could you open PR about that?

**Comment by fishballzzz** [comment]
see https://github.com/ffaker/ffaker/pull/478

**Comment by marocchino** [comment]
I think this one is rude for hongkong people and kind of bandalism. I don't want to understand your motivation, but if you want to make this change, first remove Hong Kong and Macau from the [country code list](https://en.wikipedia.org/wiki/List_of_country_calling_codes).

**Comment by marocchino** [comment]
<img width="207" alt="Screen Shot 2021-02-25 at 10 04 25" src="https://user-images.githubusercontent.com/128431/109087475-e2bc1c80-7750-11eb-9ea0-b7b52a2d21c5.png">

**Comment by marocchino** [comment]
To add that you might have misunderstood it, I'm not telling you to edit that page. The country code is set by the ITU, and it is irrelevant to us that you do not recognize them as countries.
