### ISSUE TITLE
Number Numeric Decimal Digits

### ISSUE THREAD

**Issue by skoomer** [ffaker/ffaker#481]
Good afternoon, tell me where to find in your gem ffaker 

Number Numeric Decimal Digits Date ?

**Comment by Volosh1n** [comment]
Hello @skoomer!
Number could be randomized with [Ruby's Random](https://ruby-doc.org/core-2.4.0/Random.html).
Date could be found [here](https://github.com/ffaker/ffaker/blob/main/REFERENCE.md#ffakertime).

**Comment by Volosh1n** [comment]
Feel free to reopen if you have any related questions
