### ISSUE TITLE
Custom modules?

### ISSUE THREAD

**Issue by ngan** [ffaker/ffaker#498]
Hi, more of a question than an issue.. is there a blessed way to add custom modules for domain specific fake data? Or do we just `FFaker.autoload(...)`?

**Comment by Volosh1n** [comment]
Hi!
Do you mean you need require some specific module of FFaker to some file? 

Like this?
```ruby
require 'ffaker/lorem'
```

**Comment by ngan** [comment]
Sorry, I wasn't clear. I can get specific... `FFaker` doesn't have a `Number` module that `Faker` has: https://github.com/faker-ruby/faker/blob/master/lib/faker/default/number.rb

Reading other issues, it seems that the maintainers of this gem isn't too keen on adding a Number module...which I get, kind of. We'd like to switch to `FFaker`, but we use `Faker::Number.number(digits: 9)` a lot. I get that you can do `FFaker.numerify('#########')` but the difference here is that Faker's implementation ensures a non-zero leading number, resulting in you _always_ getting a 9-digit long integer (which is what Faker::Number returns).

I was going to port over some `Faker::Number` features in my codebase and was wondering what's the best way I can add more custom functionality to the existing `FFaker` library.

**Comment by AlexWayfer** [comment]
> Hi, more of a question than an issue..

Hello. To be honest, Discussions is more proper place for questions on GitHub: https://github.com/ffaker/ffaker/discussions/categories/q-a



> We'd like to switch to `FFaker`

If it's not a secret, why? Just curious.



> but we use `Faker::Number.number(digits: 9)` a lot

For what kind of data? Is it a phone number, bank card number, ID/document number, or something more custom/specific? I mean, probably you should use more precise generator if it's available.



> I get that you can do `FFaker.numerify('#########')` but the difference here is that Faker's implementation ensures a non-zero leading number, resulting in you _always_ getting a 9-digit long integer (which is what Faker::Number returns).

Do you want to create a String of digits and then convert it to 9-digits Integer?… it sounds weird.

OK, the first work-around is adding a custom digit to generation, like `FFaker.numerify("#{rand(1..9)}########")`.

The second, maybe for simpler for you, is just random from numbers themselves, like `rand 100_000_000..999_999_999`.

It's not an answer to your original question BTW. I guess yes, you can define modules and require them or even add the `autoload`, as you wish.

Oh, now I get "custom modules for domain specific fake data" — you talked about company/product/projects 's domain.

**Comment by ngan** [comment]
> https://github.com/ffaker/ffaker/discussions/categories/q-a

Please let me know if you’d like to move the conversation there. Happy to do so 😃 It’s hard to tell if repos prefer that or not. It’s trending there it seems.

> If it's not a secret, why? Just curious.

Faker is a _massive_ ecosystem of random generators that any given project will only use a small percentage of. You can arguably say the same for FFaker. However, we’ve identified that `Faker` [uses `i18n` and adds to the locales path](https://github.com/faker-ruby/faker/blob/master/lib/faker.rb#L11). This is not great in the world of Rails since those locales can we reloaded at various times in development. It also adds a good amount of time to have everything be loaded on boot, especially for tests (even with Spring). I really like that `FFaker` autoloads/lazyloads everything. Hence we’re trying to make the switch.

> For what kind of data?

I’m not certain to be honest. We have a very, very large monolith and deal with $ and people data. I think most of the time leading-0 is fine. The problem is we have hundreds of engineers and they’ve grown accustom to “give me a 6-digit number” and expect a `Integer` that is 6 digits long. Nothing does this right out of the box for FFaker without the tricks that you’ve mentioned above.

> Do you want to create a String of digits and then convert it to 9-digits Integer?… it sounds weird.

I don’t disagree…but it’s hard to know why people need that in my environment 😅 . Maybe they want to write a test case that handles a 4-digit dollar amount, which makes leading 0’s not OK. So it comes down to: `Faker::Number.number(digits: 4)` is much easier to understand than `Integer(FFaker.numerify("#{rand(1..9)}###"))` (IMHO).

If `FFaker` doesn’t want to support this then we can easily extend it.

**Comment by AlexWayfer** [comment]
> Please let me know if you’d like to move the conversation there. Happy to do so  It’s hard to tell if repos prefer that or not. It’s trending there it seems.

I see such button, but the issue still will be here, so I don't think it's advisable and I almost have no problems with discussion here.

![image](https://user-images.githubusercontent.com/6510020/128040902-bb2681af-24d7-4280-84a8-19baa4f0625e.png)

---

Thank you for switching from Faker explanation.

---



> So it comes down to: `Faker::Number.number(digits: 4)` is much easier to understand than `Integer(FFaker.numerify("#{rand(1..9)}###"))` (IMHO).

I can agree, but what about `rand 1_000..9_999`?



> If `FFaker` doesn’t want to support this then we can easily extend it.

Yep, and as I understood, you had question about how to do it. Did you try some approach, starting from simple module definition, and faced with some troubles? Or just looking for "the best way"?

**Comment by ngan** [comment]
> but what about rand 1_000..9_999?

Yea, I think that'll be fine. I'll report back if have any other cases to cover.

> and faced with some troubles? Or just looking for "the best way"?

I haven't tried yet, but I don't imagine any troubles. This post was more of a "looking for the best way" 😄 

Thank you for being so responsive!

**Comment by AlexWayfer** [comment]
> > and faced with some troubles? Or just looking for "the best way"?
> 
> I haven't tried yet, but I don't imagine any troubles. This post was more of a "looking for the best way" 
> 
> Thank you for being so responsive!

OK. Sorry for not proper response, probably, I had switched to a project with Faker instead of FFaker, and had not working for a long time recently on the last one, but I guess there is an easiest way is a good way, also you can take a look into sources (are there some `autoload`s), also I'm ready to help you with problems.

But we all remember that for QA's there is a better place now. 😅 I'm not too familiar with some GitHub separations, but I guess it'd be better for all of us to stick with them.

**Comment by ngan** [comment]
I've re-raised the discussion and moved it here: https://github.com/ffaker/ffaker/discussions/503
