### ISSUE TITLE
FFaker::Image.file OpenURI::HTTPError

### ISSUE THREAD

**Issue by gusailov** [ffaker/ffaker#526]
FFaker::Image.file
/usr/share/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open-uri.rb:364:in `open_http': 520  (OpenURI::HTTPError)

problem is at https://dummyimage.com side
it doesn't want to work with _?text=_ and some _color_ params
for example
this works
https://dummyimage.com/600x400/000/0011ff.png
and this not
https://dummyimage.com/600x400/b033b0/0011ff.png

**Comment by yaroslavrick** [comment]
FFaker::Image.url - does not work properly too

**Comment by AlexWayfer** [comment]
> and this not
> https://dummyimage.com/600x400/b033b0/0011ff.png

![image](https://github.com/ffaker/ffaker/assets/6510020/2d195999-a62e-4e3c-8245-8a43d23769f7)

---

Now everything works:

```ruby
~/Projects/ruby/ffaker (main|✔)
> pry
pry: main > require_relative 'lib/ffaker'
# => true
pry: main > FFaker::Image.file
# => #<File:/tmp/ffaker_image20230824-117266-e5cm8v>
pry: main > FFaker::Image.url
# => "https://dummyimage.com/300x300/dc53e2/453b31.png?text="
```
