### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by professor** [ffaker/ffaker#539]
I'd like to contribute a UUID method to the FFaker API, but I'm not sure which class to stick it on.

The output would look like `929ef6ef-b11f-38c9-111b-accd67a258b2`

**Comment by Volosh1n** [comment]
Can GUID fit for those purposes?
https://github.com/ffaker/ffaker/blob/main/REFERENCE.md#ffakerguid

**Comment by AlexWayfer** [comment]
> Can GUID fit those purposes? https://github.com/ffaker/ffaker/blob/main/REFERENCE.md#ffakerguid

https://stackoverflow.com/a/246935/2630849

Should we add aliases?

**Comment by professor** [comment]
Thank you for pointing me to GUID.

I would suggest that we do not alias UUID to GUID. In my code base I plan to call ` FFaker::Guid.guid.downcase` for my UUID. It's possible that a `FFaker::Guid.uuid` or `FFaker::Uuid.uuid` could use the implementation `FFaker::Guid.guid.downcase` -- I'm happy to do this but would like guidance on what to call it.
