### ISSUE TITLE
Birthday

### ISSUE THREAD

**Issue by professor** [ffaker/ffaker#540]
I'm exploring if there's interest in Birthday. When creating users, it allows us to have realistic looking dates for employees. 

I've looked at leveraging `FFaker::Date.between`, but it's pretty clunky for the caller to setup the `from` date and `to` date. The caller could do something like `FFaker::Date.between(Time.zone.today - 365*65, Time.zone.today - 365*18)` assuming the caller had access to active support. This is my Plan B.

Faker defines birthday as:
```
# Random birthday date (maximum age between 18 and 65)
# Keyword arguments: min_age, max_age
Faker::Date.birthday(min_age: 18, max_age: 65) #=> "Fri, 28 Mar 1986"
```

What do you think? Should I add this to FFaker::Date ?

**Comment by marocchino** [comment]
Using time zones will not work in projects that do not use Rails. I recommend just doing it as a date.

**Comment by AlexWayfer** [comment]
> `Faker::Date.birthday(min_age: 18, max_age: 65)`

I'm OK with this syntax.
