### ISSUE TITLE
Random Number and Random Text

### ISSUE THREAD

**Issue by vizjerai** [ffaker/ffaker#89]
These only work in `ruby 1.9.3` because of the `rand` method but it shouldn't be hard to make it work with `ruby 1.8.7`. The idea of getting a random number between a range and random text of a specific range comes from the `Forgery` gem but it is no longer being maintained.

``` ruby
module Faker

  # picks a random number between :at_least and :at_most inclusive
  def self.number(options = {})
    options = {:at_least => 5, :at_most => 10}.merge(options)
    if options[:at_least].is_a?(Integer) && options[:at_most].is_a?(Integer)
      rand(options[:at_least]..options[:at_most])
    else
      rand(options[:at_most] - options[:at_least]) + options[:at_least]
    end
  end

end
```

``` ruby
module Faker
  module String

    SPECIAL = k(%w{! ' @ # $ % ^ & * ( ) _ + - = [ ] { } ; : " , . / ?})

    # picks a random set with a length of :exactly or
    # :at_least to :at_most characters
    def self.text(options = {})
      options = {
        :at_least      => 10,
        :at_most       => 15,
        :allow_lower   => true,
        :allow_upper   => true,
        :allow_numeric => true,
        :allow_special => false,
        :exactly       => nil}.merge(options)

      allowed_characters = []
      allowed_characters.concat(LOWERS)  if options[:allow_lower]
      allowed_characters.concat(UPPERS)  if options[:allow_upper]
      allowed_characters.concat(NUMBERS) if options[:allow_numeric]
      allowed_characters.concat(SPECIAL) if options[:allow_special]

      length = options[:exactly] || Faker.number(options)
      (1..length).map { allowed_characters.sample }.join
    end

  end
end
```

**Comment by AlexWayfer** [comment]
> Consider: rand(10) + 10 vs Faker.number(at_least: 10, at_most: 20), the second one reads nicer but is not clear if the bounds are inclusive or exclusive. maybe we could use a range: Faker.number(0...100) -> 0 to 99, number(0..100) -> 0 to 100.

The last option (with Ranges) is good. I also suggest `.numbers(1..10, 5)` method for generation collection of 5 different (unique) numbers in `1..10`.

**Comment by AlexWayfer** [comment]
>  I also suggest .numbers(1..10, 5) method for generation collection of 5 different (unique) numbers in 1..10.

Oh, maybe there are should be `FFaker::UniqueUtils`:

```ruby
FFaker::UniqueUtils.new(FFaker.number(1..10), 5)
```

**Comment by AlexWayfer** [comment]
Also there can be `FFaker::Numeric.integer(1..10)` (and possibly `FFaker::Numeric.float(0.0...5.0)`) instead of `FFaker.number(1..10)`.

**Comment by jonathonnordquist** [comment]
Does this gem seriously lack the ability to do something as simple as generating random numbers?  I'm having to generate a phone number, then `gsub` the periods out and convert the resulting string to an integer just to get a random number.

**Comment by Volosh1n** [comment]
@jonathonnordquist 
```ruby
FFaker.numerify('#####-#-##') # => "25695-7-39"
```
